# Description: Tools to configure and manipulate wlan devices
# URL: http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html

name=wireless-tools
version=29
release=1
source=(http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/${name/-/_}.$version.tar.gz)

build() {
  cd ${name/-/_}.$version

  make CC="$HOST-gcc"
  make PREFIX=$PKG/usr INSTALL_MAN=$PKG/usr/share/man install
}
