# Description: Perfect hash function generator
# URL: http://www.gnu.org/software/gperf

name=gperf
version=3.0.4
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)

build() {
    cd $name-$version
    ./configure --prefix=/usr --mandir=/usr/man \
                --build=$BUILD \
                --host=$HOST
    make
    make DESTDIR=$PKG install
    rm -r $PKG/usr/share
}

