# Description: A cross toolchain builder
# URL: http://ymorin.is-a-geek.org/projects/crosstool

name=crosstool-ng
version=1.15.2
release=1
source=(http://crosstool-ng.org/download/$name/$name-$version.tar.bz2
        arm-cortex_a9-linux-gnueabi.config)

build() {
    cd $name-$version

    ./configure --enable-local
    make

    # Disable fakeroot (temporarily)
    TEMP_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
    TEMP_LD_PRELOAD=$LD_PRELOAD
    unset LD_LIBRARY_PATH
    unset LD_PRELOAD

    # Do ct-ng configuration
    cp $SRC/arm-cortex_a9-linux-gnueabi.config .config
    sed -i /^CT_LOCAL_TARBALLS_DIR=/s:=.*:=\"$BG_SOURCE_DIR\": .config
    sed -i /^CT_PREFIX_DIR=/s:=.*:=\"$PKG\": .config

    ./ct-ng build

    # Cleanup host sysroot
    rm -rf $PKG/arm-cortex_a9-linux-gnueabi/sysroot/etc
    rm -rf $PKG/arm-cortex_a9-linux-gnueabi/sysroot/usr/share

    # Enable fakeroot again
    export LD_LIBRARY_PATH=$TEMP_LD_LIBRARY_PATH
    export LD_PRELOAD=$TEMP_LD_PRELOAD
}
