# Description: Library of PNG support functions
# URL: http://www.libpng.org

name=libpng
version=1.5.10
release=1
source=(ftp://ftp.simplesystems.org/pub/$name/png/src/$name-$version.tar.xz)
depends=cross/zlib

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;
}

