# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org

name=gst-plugins-good
version=0.11.91
release=1
source=(http://gstreamer.freedesktop.org/src/gst-plugins-good/$name-$version.tar.xz)
depends=(cross/glib cross/gstreamer cross/gst-plugins-base)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST \
               --disable-oss4 \
               --disable-oss \
               --disable-gst_v4l2

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/locale

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $CROSS_SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$CROSS_SYSROOT/usr;g" {} \;
}

