# Description: Clean Qt WenbKit1 browser
# URL:

name=stripped-browser
version=0.1
release=1
source=(sftp://ixonos@ixonos01.novipark.dk/source/stripped-browser-$version.tar.gz)
depends=(qtwebkit)

build() {
   cd $name-$version

   PATH=$SYSROOT/opt/qt5-native/bin:$PATH

   qmake

   make -j $JOBS

   make INSTALL_ROOT=$PKG/tmp install
   mv $PKG/tmp/$SYSROOT/* $PKG
   rm -rf $PKG/tmp
}
