# Description: A basic GNU/linux filesystem
# URL: http://www.buildgear.org

name=fs
version=1.0
release=1
options=(nostrip)
source=(asound.conf)
depends=(core
         u-boot
         linux
         net-tools
         traceroute
         alsa-utils
         connman
         vim
         gstreamer
         gst-plugins-base
         gst-plugins-good
         gst-plugins-bad
         gst-plugins-ugly
         gstreamer-imx
         imx-gpu-viv
         qtwebkit
         qtwebkit-examples
         CinematicExperience)

build() {
   # Copy fully populated sysroot
   cp -a $SYSROOT/* $PKG

   # Set host name
   echo "hummingboard" > $PKG/etc/hostname

   # Set login issue
   echo -e "Hummingboard Mini Distribution $version\n" > $PKG/etc/issue

   # Add ALSA configuration (use onboard audio by default)
   install -m 0644 $SRC/asound.conf $PKG/etc

   # Cleanup
   rm -r $PKG/opt/qt5-native
   cd $PKG/usr/include; rm -rf !(python|python?.?)
   find $PKG/usr/lib -name '*.a'    -delete -o \
                     -name '*.la'   -delete

   # Create tarball
   tar -C $PKG -Ipixz -cpf $OUTPUT/fs.tar.xz .
}

check() {
   check_tool pixz "Available in Ubuntu package pixz"
}
