# Description: An sh-compatible command language interpreter
# URL: http://cnswww.cns.cwru.edu/~chet/bash/bashtop.html

name=bash
version=4.2
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz \
        bash-4.2-patches.tar.gz profile)
depends=(cross/ncurses)

build() {
  cd $name-$version
  
  cat $SRC/bash42-0?? | patch -p0

  echo "bash_cv_sys_named_pipes=yes" >> config.cache
  echo "bash_cv_job_control_missing=present" >> config.cache

  touch configure
  ./configure --build=$BUILD \
              --host=$HOST \
              --cache-file=config.cache \
              --prefix=/usr \
              --exec-prefix= \
              --mandir=/usr/man \
              --disable-nls \
              --without-bash-malloc \
              --with-curses
  make 
  install -D -m 755 bash $PKG/bin/bash
  install -D -m 644 doc/bash.1 $PKG/usr/man/man1/bash.1
  install -D -m 644 $SRC/profile $PKG/etc/profile

  ln -s bash $PKG/bin/sh
  ln -s bash.1 $PKG/usr/man/man1/sh.1
}
