# Description: ALSA libraries
# URL: http://www.alsa-project.org

name=alsa-lib
version=1.0.24.1
release=1
source=(ftp://ftp.alsa-project.org/pub/lib/$name-$version.tar.bz2)

build() {
  cd $name-$version

  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --disable-python 

  make -j $JOBS
  make DESTDIR=$PKG install

  # Fix .la files
  find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;
}
