# Description: The man page suite used to read most of the documentation for Linux
# URL: http://primates.ximian.com/~flucifredi/man/

name=man
version=1.6g
release=1
source=(http://primates.ximian.com/~flucifredi/man/$name-$version.tar.gz makewhatis)
depends=(cross/groff cross/less)

build() {
  cd $name-$version

  ./configure -prefix=/usr \
              -confdir=/etc \
              -mandir=/usr/share/man \
              +lang none \
              -default

  make CC="$HOST-gcc"
  make DESTDIR=$PKG install
  install -D -m 755 $SRC/makewhatis $PKG/etc/cron/daily/makewhatis
}
