# Description: U-boot - The universal bootloader
# URL:         http://www.denx.de/wiki/U-Boot
# Builder:     Martin Lund <martin.lund@keep-it-simple.com>

name=u-boot
version=2011.09
release=1
source=(ftp://ftp.denx.de/pub/$name/$name-$version.tar.bz2)

build(){
    cd $name-$version
    make ARCH=arm CROSS_COMPILE=$HOST- omap4_panda_config
    make ARCH=arm CROSS_COMPILE=$HOST-

    cp u-boot.bin $BLD/
    cp u-boot.bin $PKG/
    cp MLO $BLD/
    cp MLO $PKG/
}
