# Description: The Linux kernel
# URL: http://www.kernel.org

name=linux
version=3.6
release=1
source=(http://www.kernel.org/pub/$name/kernel/v3.0/$name-$version.tar.xz
        omap4-pandaboard-wlan-fix.patch
        pandaboard.config)

build(){
   cd $name-$version

   cp $SRC/pandaboard.config .config

   patch -p1 < $SRC/omap4-pandaboard-wlan-fix.patch

   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- uImage
   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- modules
   make ARCH=arm CROSS_COMPILE=$HOST- INSTALL_MOD_PATH=$PKG modules_install

   cp arch/arm/boot/uImage $OUTPUT/
}

check() {
   # Test for preinstalled mkimage tool
   check_tool mkimage
}
