# Description: The Linux kernel
# URL: http://www.kernel.org

name=linux
version=3.7.1
release=1
depends=(native/linux-source)

build(){
   cd $NATIVE_SYSROOT/usr/src/linux

   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- uImage
   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- modules
   make ARCH=arm CROSS_COMPILE=$HOST- INSTALL_MOD_PATH=$PKG modules_install

   # Cleanup
   rm $PKG/lib/modules/$version/build
   rm $PKG/lib/modules/$version/source

   cp arch/arm/boot/uImage $OUTPUT/
}

check() {
   # Test for preinstalled mkimage tool
   check_tool mkimage
}
