# Description: A tool to trace the route of ip packets
# URL: ftp://ftp.ee.lbl.gov/

name=traceroute
version=2.0.18
release=1
source=(http://heanet.dl.sourceforge.net/project/$name/$name/$name-$version/$name-$version.tar.gz)

build() {
  cd $name-$version

  make CROSS="$HOST-" LDFLAGS="-L../libsupp -s"
  make DESTDIR=$PKG prefix=/usr mandir=/usr/share/man install
}
