# Description: 
# URL: 

name=attr
version=2.4.46
release=1
source=(http://mirrors.zerg.biz/nongnu/attr/$name-$version.src.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST
   make
   make DIST_ROOT=$PKG install install-lib install-dev

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;
}

