# Description: A cross toolchain builder
# URL: http://www.crosstool-ng.org

name=crosstool-ng
version=1.22.0
release=1
source=(http://crosstool-ng.org/download/$name/$name-$version.tar.xz
        disable-LD_LIBRARY_PATH-check.patch
        $HOST.config)
options=(nostrip)

build() {
   cd $name

   patch -p1 -i $SRC/disable-LD_LIBRARY_PATH-check.patch

   ./configure --enable-local
   make -j $JOBS

   # Do ct-ng configuration
   cp $SRC/$HOST.config .config
   sed -i /^CT_LOCAL_TARBALLS_DIR=/s:=.*:=\"$SOURCE\": .config
   sed -i /^CT_PREFIX_DIR=/s:=.*:=\"$PKG\": .config
#   sed -i /^CT_KERNEL_LINUX_CUSTOM_LOCATION=/s:=.*:=\"$SYSROOT/usr/src/linux\": .config

   ./ct-ng build

   # Clean up host sysroot
   rm -r $PKG/$HOST/sysroot/etc
   rm -r $PKG/$HOST/sysroot/usr/share
   mv $PKG/$HOST/sysroot/sbin/* $PKG/$HOST/sysroot/usr/sbin
   rmdir $PKG/$HOST/sysroot/sbin

   # Add ld-linux.so.3 link pointing to ld-linux-armhf.so.3
   # Added for compatibility - only required for hard float configurations.
   ln -s ld-linux-armhf.so.3 $PKG/$HOST/sysroot/lib/ld-linux.so.3

   # Make gnu/stubs.h a soft link to gnu/stubs-hard.h
   rm $PKG/$HOST/sysroot/usr/include/gnu/stubs.h
   ln -s stubs-hard.h $PKG/$HOST/sysroot/usr/include/gnu/stubs.h

   # Fix .la files
   find $PKG/$HOST/sysroot/lib -name "*.la" -exec sed -i -e "/libdir/s;'/lib;'`readlink -f $CROSS_SYSROOT`/lib;g" {} \;
   find $PKG/$HOST/sysroot/usr/lib -name "*.la" -exec sed -i -e "/libdir/s;'/usr/lib;'`readlink -f $CROSS_SYSROOT`/usr/lib;g" {} \;
}

check() {
   # Test for preinstalled tools and libs
   check_tool gawk
   check_tool bison
   check_tool flex
   check_tool gperf
   check_tool makeinfo
   check_tool libtool
   check_tool help2man
   check_exist /usr/include/curses.h
   check_exist /usr/include/expat.h
}
