# Description: Basic sysvinit init scripts

name=sysvinit
version=0.1
release=1
source=(inittab rcS)
depends=cross/fs-skeleton

build(){
	mkdir -p $PKG/etc/init.d
	cp $SRC/inittab $PKG/etc/
	cp $SRC/rcS $PKG/etc/init.d/
	chmod 744 $PKG/etc/init.d/rcS
}
