# Description: Firmware for WL1271 wifi/bluetooth chip
# URL: git://git.kernel.org/pub/scm/linux/kernel/git/dwmw2/linux-firmware.git

name=wl1271-firmware
version=1.0
release=1
source=(wl1271-fw-2.bin wl1271-fw-ap.bin wl1271-fw.bin wl1271-nvs.bin wl127x-fw-4-sr.bin)

build() {
   mkdir -p $PKG/lib/firmware/ti-connectivity
   cp $SRC/{wl1271-fw-2.bin,wl1271-fw-ap.bin,wl1271-fw.bin,wl1271-nvs.bin,wl127x-fw-4-sr.bin} $PKG/lib/firmware/ti-connectivity
}

