# Description: Linux - The Linux kernel
# URL:         http://www.kernel.org
# Builder:     Martin Lund <martin.lund@keep-it-simple.com>

name=linux
version=3.4-rc4
release=1
source=(http://www.kernel.org/pub/$name/kernel/v3.0/testing/$name-$version.tar.bz2
	linux.config)

build(){
    cd $name-$version

    cp $SRC/linux.config .config

    make ARCH=arm CROSS_COMPILE=$HOST- uImage
    make ARCH=arm CROSS_COMPILE=$HOST- modules
    make ARCH=arm CROSS_COMPILE=$HOST- INSTALL_MOD_PATH=$PKG modules_install

    cp arch/arm/boot/uImage $BLD/
#    cp arch/arm/boot/uImage $PKG/
}
