# Description: The Linux kernel
# URL: http://www.kernel.org

name=linux
version=3.4
release=1
source=(http://www.kernel.org/pub/$name/kernel/v3.0/testing/$name-$version.tar.xz
	linux.config)

build(){
    cd $name-$version

    cp $SRC/linux.config .config

    make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- uImage
    make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST- modules
    make ARCH=arm CROSS_COMPILE=$HOST- INSTALL_MOD_PATH=$PKG modules_install

    cp arch/arm/boot/uImage $BLD/
}
