# Description: Library of PNG support functions
# URL: http://www.ijg.org/

name=libjpeg
version=8d
release=1
source=(http://www.ijg.org/files/jpegsrc.v$version.tar.gz)

build() {
   cd jpeg-8d

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST 
   make
   make DESTDIR=$PKG install
}
