# Description: A cross toolchain builder
# URL: http://www.crosstool-ng.org

name=crosstool-ng
version=1.18.0
release=1
source=(http://crosstool-ng.org/download/$name/$name-$version.tar.bz2
        disable-LD_LIBRARY_PATH-check.patch
        $HOST.config)
depends=(native/linux-source)

build()
{
   cd $name-$version

   patch -p1 -i $SRC/disable-LD_LIBRARY_PATH-check.patch

   ./configure --enable-local
   make

   # Do ct-ng configuration
   cp $SRC/$HOST.config .config
   sed -i /^CT_LOCAL_TARBALLS_DIR=/s:=.*:=\"$SOURCE\": .config
   sed -i /^CT_PREFIX_DIR=/s:=.*:=\"$PKG\": .config
   sed -i /^CT_KERNEL_LINUX_CUSTOM_LOCATION=/s:=.*:=\"$SYSROOT/usr/src/linux\": .config

   ./ct-ng build

   # Clean up host sysroot
   rm -r $PKG/$HOST/sysroot/etc
   rm -r $PKG/$HOST/sysroot/usr/share
   mv $PKG/$HOST/sysroot/sbin/* $PKG/$HOST/sysroot/usr/sbin
   rmdir $PKG/$HOST/sysroot/sbin

   # Add ld-linux.so.3 link pointing to ld-linux-armhf.so.3
   # Added for compatibility - only required for hard float configurations.
   ln -s ld-linux-armhf.so.3 $PKG/$HOST/sysroot/lib/ld-linux.so.3

   # Fix .la files
   sed -i -e "/libdir/s:=.*:='$CROSS_SYSROOT/lib':" \
       $PKG/$HOST/sysroot/lib/libstdc++.la \
       $PKG/$HOST/sysroot/lib/libsupc++.la
}

check()
{
   # Test for preinstalled tools and libs
   check_tool gawk
   check_tool bison
   check_tool flex
   check_tool gperf
   check_tool makeinfo "Can be found in the Ubuntu repos in package texinfo"
   check_tool libtool
   check_exist /usr/include/curses.h "Can be found in the Ubuntu repos in package libncurses5-dev"
   check_exist /usr/include/expat.h "Can be found in the Ubuntu repos in package libexpat1-dev"
}
