# Description: U-boot - The universal bootloader
# URL: https://github.com/SolidRun/u-boot-imx6
# License: GPLv2

name=u-boot
version=git408544d6
release=1
source=(http://mirror.mini-distribution.io/solidrun/solidrun-u-boot-imx6-$version.tar.xz uEnv.txt)

build(){
    cd solidrun-u-boot-imx6-$version

    make ARCH=arm CROSS_COMPILE=$HOST- mx6_cubox-i_config
    make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST-

    mkdir -p $PKG/boot
    cp $SRC/uEnv.txt $PKG/boot

    cp u-boot.img $OUTPUT
    cp SPL $OUTPUT
}
