# Description: U-boot - The universal bootloader
# URL: https://github.com/SolidRun/u-boot-imx6

name=u-boot
version=gite4bc4c3
release=1
source=(http://buildgear.org/mirror/solidrun/solidrun-u-boot-imx6-gite4bc4c3.tar.xz uEnv.txt)

build(){
    cd solidrun-u-boot-imx6-gite4bc4c3

    make ARCH=arm CROSS_COMPILE=$HOST- mx6_cubox-i_config
    make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST-

    mkdir -p $OUTPUT/boot
    cp $SRC/uEnv.txt $OUTPUT/boot

    cp u-boot.img $OUTPUT
    cp SPL $OUTPUT
}
