# Description: System and service manager for Linux
# URL: http://www.freedesktop.org/wiki/Software/systemd

name=systemd
version=185
release=1
source=(http://www.freedesktop.org/software/systemd/$name-$version.tar.xz)
depends=(cross/libcap
         cross/dbus
         cross/kmod
         cross/util-linux
         cross/usbutils
         cross/pciutils
         cross/glib)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;

   # Systemd target configuration

}

