# Description: Library of PNG support functions
# URL: http://www.libpng.org

name=libffi
version=3.0.11
release=1
source=(ftp://sourceware.org/pub/libffi/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info
}

