# Description: Library of PNG support functions
# URL: http://www.libpng.org

name=libffi
version=3.0.11
release=1
source=(ftp://sourceware.org/pub/libffi/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST
   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
#   find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;
}

