# Description: The Linux kernel
# URL: http://www.kernel.org

name=omapconf
version=git7138750
release=1
source=(http://buildgear.org/mirror/$name-$version.tar.xz)

build(){
   cd $name-$version

   make CROSS_COMPILE=$HOST- DESTDIR=$PKG/usr/sbin install
}
