# Description: A system for managing library compile/link flags
# URL: http://pkgconfig.freedesktop.org

name=pkg-config
version=0.26
release=1
source=(http://$name.freedesktop.org/releases/$name-$version.tar.gz)

build() {
	cd $name-$version
	./configure --prefix=$BUILD_SYSROOT/usr
	make
	make DESTDIR=$PKG install

	rm -rf $PKG/$BUILD_SYSROOT/usr/share/doc
}
