# Description: Library to deal with kernel modules
# URL: http://git.profusion.mobi/cgit.cgi/kmod.git/

name=kmod
version=8
release=1
source=(http://www.kernel.org/pub/linux/utils/kernel/kmod/$name-$version.tar.xz)

build(){
   cd $name-$version
   ./configure --prefix=/usr \
               --disable-nls \
               --build=$BUILD \
               --host=$HOST
   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;
}
