# Description: A minimal filesystem
# URL: http://www.buildgear.org

name=fs
version=1.0
release=1
depends=(cross/fs-skeleton
         cross/sysvinit
         cross/linux
         cross/dropbear
         cross/libpng
         cross/libjpeg
         cross/libusb
         cross/dhcpcd
         cross/nano
         cross/alsa-utils
         cross/openssl
         cross/systemd)

build() {
	cp -a $SYSROOT/* $PKG
	
	mkfs.jffs2 -r $SYSROOT -e 64 -o $BLD/fs.jffs2
	cd $SYSROOT
	tar zcpf $BLD/fs.tar.gz .
}
