# Description: A minimal filesystem
# URL: http://www.buildgear.org

name=fs
version=1.0
release=1
depends=(cross/fs-skeleton
         cross/coreutils
         cross/sysvinit
         cross/shadow
         cross/procps
         cross/kbd
         cross/gzip
         cross/util-linux
         cross/linux
         cross/dropbear
         cross/libpng
         cross/libjpeg
         cross/libusb
         cross/dhcpcd
         cross/findutils
         cross/bash
         cross/man
         cross/gawk
         cross/nano
         cross/kmod
         cross/grep
         cross/wget
         cross/psmisc
         cross/net-tools
         cross/iputils
         cross/wireless-tools
         cross/traceroute
         cross/alsa-utils
         cross/gst-plugins-good
         cross/openssl
         cross/systemd)

build() {
	cp -a $SYSROOT/* $PKG

        # Cleanup
        rm -rf $PKG/usr/include
        rm -rf $PKG/usr/lib/*.a
        rm -rf $PKG/usr/lib/*.la
	
        # Create JFFS2 image
	mkfs.jffs2 -r $PKG -e 64 -o $BLD/fs.jffs2

        # Create tarball
	tar -C $PKG -acpf $BLD/fs.tar.gz .
}
