# Description: The Linux kernel
# URL: http://www.kernel.org

name=linux-source
version=3.8.5
release=1
source=(http://www.kernel.org/pub/linux/kernel/v3.0/linux-$version.tar.xz
        omap4-pandaboard-wlan-fix.patch omap-ehci-clk-fix.patch
        pandaboard.config)
options=(nostrip)

build(){
   mkdir -p $PKG/usr/src
   mv linux-$version $PKG/usr/src/linux

   cd $PKG/usr/src/linux

   cp $SRC/pandaboard.config .config
   patch -p1 < $SRC/omap4-pandaboard-wlan-fix.patch
   patch -p1 < $SRC/omap-ehci-clk-fix.patch
}
