# Description: U-boot - The universal bootloader
# URL: http://www.denx.de/wiki/U-Boot

name=u-boot
version=2012.07
release=1
source=(http://ftp.denx.de/pub/$name/$name-$version.tar.bz2
        U-Boot-2-7-HACK-rearrange-link-order-for-thumb.patch)

build(){
   cd $name-$version

   patch -p1 < $SRC/U-Boot-2-7-HACK-rearrange-link-order-for-thumb.patch

   # Change default configuration to ext4
   sed -i -e "s;ext3;ext4;g" include/configs/omap4_common.h

   make ARCH=arm CROSS_COMPILE=$HOST- omap4_panda_config
   make -j $JOBS ARCH=arm CROSS_COMPILE=$HOST-

   cp u-boot.bin $OUTPUT/u-boot.img
   cp MLO $OUTPUT/
}
