# Description: Userspace device management daemon
# URL: http://www.kernel.org/pub/linux/utils/kernel/hotplug/udev.html

name=udev
version=177
release=1
source=(ftp://ftp.kernel.org/pub/linux/utils/kernel/hotplug/$name-$version.tar.bz2 \
        start_udev)

depends=(cross/util-linux cross/pciutils cross/kmod cross/gperf)

build() {
  cd udev-$version

#  autoreconf

#  BLKID_CFLAGS="something" \
#  BLKID_LIBS="something" \
#  KMOD_CFLAGS="something" \
#  KMOD_LIBS="something" \
#  USBUTILS_CFLAGS="something" \
#  USBUTILS_LIBS="something" \
  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --disable-gudev \
              --disable-introspection \
              --with-pci-ids-path=/usr/share/pci.ids

  make
  make install DESTDIR=$PKG

  mkdir -p $PKG/lib/{firmware,udev/devices/{pts,shm}}
  mkdir -p $PKG/lib

  # Install udev startup file
  install -m 0755 $SRC/start_udev $PKG/sbin

  # Remove junk
  rm -rf $PKG/usr/share/{gtk-,}doc
}
