# Description: Linux - The Linux kernel
# URL:         http://www.kernel.org
# Builder:     Martin Lund <martin.lund@keep-it-simple.com>

name=linux-modules
version=3.1
release=1
source=(http://www.kernel.org/pub/linux/kernel/v3.0/linux-$version.tar.bz2
	linux.config)

build(){
    cd linux-$version
    cp $SRC/linux.config .config

    make ARCH=arm CROSS_COMPILE=$HOST- modules
    make ARCH=arm CROSS_COMPILE=$HOST- INSTALL_MOD_PATH=$PKG modules_install
}
