# Description: BusyBox - A collection of tiny versions of many common UNIX utilities
# URL:         http://www.busybox.net
# Builder:     Martin Lund <martin@martinlund.org>

name=busybox
version=1.19.3
release=1
source=(http://$name.net/downloads/$name-$version.tar.bz2
	busybox.config)

build() {
    cd $name-$version

    cp $SRC/busybox.config .config
    make CROSS_COMPILE=$HOST-
    make CROSS_COMPILE=$HOST- CONFIG_PREFIX=$PKG install
}
