# Description: ALSA libraries
# URL: http://www.alsa-project.org
# Builder: Martin Lund <martin.lund@keep-it-simple.com>

name=alsa-lib
version=1.0.24.1
release=1
source=(ftp://ftp.alsa-project.org/pub/lib/$name-$version.tar.bz2)

build() {
  cd $name-$version
  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --disable-python 
  make
  make DESTDIR=$PKG install
}
