# Description: Library of PNG support functions
# URL: http://www.ijg.org/

name=libjpeg
version=8d
release=1
source=(http://www.ijg.org/files/jpegsrc.v$version.tar.gz)

build() {
   cd jpeg-8d

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST 

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "s;/usr;$CROSS_SYSROOT/usr;g" "{}" \;
}
