# Description: A minimal filesystem
# URL:         http://www.buildgear.org
# Builder:     Martin Lund <martin@martinlund.org>

name=fs
version=1.0
release=1
depends=(host/{filesystem,sysvinit,busybox,dropbear,libpng,libusb,dhcpcd,nano})

build() {
	cp -a $SYSROOT/* $PKG
	
	mkfs.jffs2 -r $SYSROOT -e 64 -o $BLD/fs.jffs2
	cd $SYSROOT
	tar zcpf $BLD/fs.tar.gz .
}
