# Description: Filesystem skeleton
# URL: http://www.buildgear.org

name=fs-skeleton
version=0.1
release=1
source=(group)

build(){
    # Create basic directories
    mkdir -p $PKG/usr
    mkdir -p $PKG/etc
    mkdir -p $PKG/dev
    mkdir -p $PKG/proc
    mkdir -p $PKG/sys
    mkdir -p $PKG/tmp
    mkdir -p $PKG/mnt
    mkdir -p $PKG/lib
    mkdir -p $PKG/opt
    mkdir -p $PKG/home
    mkdir -p $PKG/root
    mkdir -p $PKG/usr/{bin,sbin,include,lib,share,man}
    mkdir -p $PKG/usr/man/man{1,2,3,4,5,6,7,8}
    mkdir -p $PKG/var
    mkdir -p $PKG/run

    # Create symlinks
    ln -s /usr/bin $PKG/bin
    ln -s /usr/sbin $PKG/sbin
    ln -s ../var $PKG/usr/var

    # Create basic device nodes
#    mknod $PKG/dev/console c 5 1
#    chmod 0600 $PKG/dev/console

    # Create users
    echo "root:it3Y6aTzjxuyE:0:0:root:/root:/bin/bash" >> $PKG/etc/passwd

    # Create groups
    cp $SRC/group $PKG/etc/group

    # Create host name
    echo "panda" > $PKG/etc/hostname

    # Create issue
    echo -e "Pandaboard Mini Distribution 1.0\n" > $PKG/etc/issue

    # systemd required
    ln -s /proc/self/mounts $PKG/etc/mtab
    ln -s /usr/lib/systemd/systemd $PKG/usr/bin/init
}
