# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org

name=gstreamer
version=0.11.91
release=1
source=(http://gstreamer.freedesktop.org/src/gstreamer/$name-$version.tar.xz)
depends=cross/glib

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{gtk-doc,locale}

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $CROSS_SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$CROSS_SYSROOT/usr;g" {} \;
}

